# -*- coding: utf-8 -*-
"""PLANT_demo_embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLE3ysElImtxBBIzlGHlFTdDo8_O5aoY

Install & inmport modules
"""

# %%
import os
import shutil
import plotly
import sys, os, glob
import plotly.express as px
import plotly.colors as pc
import joblib
import pandas as pd
import numpy as np

from transformers import AutoTokenizer, EsmConfig
from torch.utils.data import DataLoader

import plotly.express as px
import plotly.graph_objects as go

import nbformat
from Bio import Align

import torch

repo_dir = "/home3/oml4h/hugging_face_downloads/PLANT_model/code"

# Delete if the directory exists
# if os.path.exists(repo_dir):
#     shutil.rmtree(repo_dir)

# # clone
# !git clone -q https://github.com/TheSatoLab/PLANT.git $repo_dir
# %%

sys.path.append("/home3/oml4h/hugging_face_downloads/PLANT_model/code/src")
sys.path.append("/home3/oml4h/PLM_SARS-CoV-2")

from plant import TextDataset, tokenize_sequences, semanticESM, set_encoders, embed_sequences
from Functions_HuggingFace import (
    plant_trim_to_target_length,
    plant_sequence_identity,
    plant_alignment_coverage_metrics,
    plant_extract_year,
)

print("Imported plant module OK.")

"""Definition of hyperparameters"""

scale_factor = 8
# Repository ID on HF
REPO_ID = "TheSatoLab-UTokyo/PLANT"
SUBFOLDER = "variants/PLANT_fixed"

BACKGROUND_CSV_PATH = "/home3/oml4h/hugging_face_downloads/PLANT_model/code/examples/backgrounds.csv"

# Please specify your data of interest here
CSV_PATH = "/home3/oml4h/PLM_SARS-CoV-2/Sequences/PLANT_input_file.csv" # obtained from nextclade example data

outdir="/home3/oml4h/PLM_SARS-CoV-2/Results/PLANT_results"
os.makedirs(outdir, exist_ok=True)
"""Load model"""
# %%
# from huggingface_hub import snapshot_download

# local_hf_dir = snapshot_download(
#     repo_id=REPO_ID,
#     repo_type="model",
#     allow_patterns=[
#         f"{SUBFOLDER}/*.safetensors",  # Corrected pattern
#         f"{SUBFOLDER}/*.joblib",
#         f"{SUBFOLDER}/*.index.json",
#         f"{SUBFOLDER}/config.json",
#     ],
# )

# Use local downloaded model
local_hf_dir = "/home3/oml4h/hugging_face_downloads/PLANT_model"
# %%
print("HF snapshot dir:", local_hf_dir)

CKPT_DIR = os.path.join(local_hf_dir, SUBFOLDER)
print("Checkpoint dir:", CKPT_DIR)

single_path = os.path.join(CKPT_DIR, "model.safetensors")
shard_paths = sorted(glob.glob(os.path.join(CKPT_DIR, "model-*-of-*.safetensors")))

assert (os.path.exists(single_path) or len(shard_paths) > 0), \
    f"safetensors not found under {CKPT_DIR}. Check uploaded filenames."

# ===== Automatically detect OneHotEncoder (joblib) =====
def find_file(patterns):
    for pat in patterns:
        paths = glob.glob(os.path.join(local_hf_dir, "**", pat), recursive=True)
        if len(paths) > 0:
            return paths[0]
    return None

virus_enc_path = find_file(["virus_encoder.joblib", "**/virus_encoder.joblib"])
ref_enc_path   = find_file(["ref_encoder.joblib",   "**/ref_encoder.joblib"])
vp_enc_path    = find_file(["vp_encoder.joblib",    "**/vp_encoder.joblib"])
rp_enc_path    = find_file(["rp_encoder.joblib",    "**/rp_encoder.joblib"])

for p, name in [(virus_enc_path,"virus"), (ref_enc_path,"ref"), (vp_enc_path,"vp"), (rp_enc_path,"rp")]:
    assert p is not None, f"{name}_encoder.joblib not found. Please confirm it is uploaded to the HF repo."
    print(f"Found {name} encoder:", p)

# Load joblib and inject into model

ohe_v  = joblib.load(virus_enc_path)
ohe_r  = joblib.load(ref_enc_path)
ohe_vp = joblib.load(vp_enc_path)
ohe_rp = joblib.load(rp_enc_path)
set_encoders(ohe_v, ohe_r, ohe_vp, ohe_rp)
print("Encoders set.")

"""Load data"""

# %%

# === Load data of interest===
df = pd.read_csv(CSV_PATH)

print(df.head())
print(f"\nInitial number of sequences: {len(df)}")

# Check sequence lengths before filtering
seq_lengths = df["seq"].str.len()
print(f"Sequence length distribution:\n{seq_lengths.value_counts().sort_index()}")

# Use a J.2 reference sequence (329 aa) for alignment
REFERENCE_SEQ = "QKIPGNDNSTATLCLGHHAVPNGTIVKTITNDRIEVTNATELVQNSSIGKICNSPHQILDGGNCTLIDALLGDPQCDGFQNKEWDLFVERSRANSSCYPYDVPDYASLRSLVASSGTLEFKDESFNWTGVKQNGKSSACKRGSSSSFFSRLNWLTSLNNIYPAQNVTMPNKEQFDKLYIWGVHHPDTDKNQFSLFAQSSGRITVSTTRSQQAVIPNIGSRPRVRDIPSRISIYWTIVKPGDILLINSTGNLIAPRGYFKIRSGKSSIMRSDAPIGECKSECITPNGSIPNDKPFQNVNRITYGACPRYVKQSTLKLATGMRNVPEKQTR"
TARGET_LENGTH = 329

ALIGN_IDENTITY_WARN = 0.90
ALIGN_IDENTITY_FAIL = 0.80
ALIGN_REF_COVERAGE_WARN = 0.98
ALIGN_REF_COVERAGE_FAIL = 0.95

def trim_to_target_length(seq, reference=REFERENCE_SEQ, target_len=TARGET_LENGTH):
    """Wrapper around shared helper in Functions_HuggingFace."""
    return plant_trim_to_target_length(seq, reference, target_len, return_start_pos=False)


def sequence_identity(a, b):
    """Wrapper around shared helper in Functions_HuggingFace."""
    return plant_sequence_identity(a, b)


def alignment_coverage_metrics(seq, reference=REFERENCE_SEQ):
    """Wrapper around shared helper in Functions_HuggingFace."""
    return plant_alignment_coverage_metrics(seq, reference)

# Apply trimming
print("\nTrimming sequences to 329 amino acids...")
df["seq_raw"] = df["seq"]
df["seq_trimmed"] = df["seq"].apply(trim_to_target_length)

# Remove sequences that couldn't be trimmed
before_trim_filter = len(df)
df = df[df["seq_trimmed"].notna()].copy()
print(f"Sequences after trimming filter: {len(df)} (removed {before_trim_filter - len(df)})")

# Update seq column with trimmed sequences
df["seq"] = df["seq_trimmed"]
df = df.drop(columns=["seq_trimmed"])


# filtering for invalid amino acids
df = df[~df["seq"].str.contains("X|B|\\*", regex=True).fillna(False)]


# Final length check
df = df[df["seq"].str.len() == TARGET_LENGTH]
df = df.reset_index(drop=True)
print(f"Final number of sequences: {len(df)}")

# Alignment quality check: identity to reference after alignment-based trimming
df["identity_to_reference"] = df["seq"].apply(lambda s: sequence_identity(s, REFERENCE_SEQ))
print("\nAlignment identity summary (vs reference):")
print(df["identity_to_reference"].describe(percentiles=[0.05, 0.25, 0.5, 0.75, 0.95]))

low_identity = df[df["identity_to_reference"] < ALIGN_IDENTITY_WARN].copy()
if len(low_identity) > 0:
    print(f"WARNING: {len(low_identity)} sequences below {ALIGN_IDENTITY_WARN:.2f} identity.")
    cols = [c for c in ["name", "subclade", "identity_to_reference"] if c in low_identity.columns]
    print(low_identity[cols].sort_values("identity_to_reference").head(20))

assert df["identity_to_reference"].min() >= ALIGN_IDENTITY_FAIL, (
    f"Alignment QC failed: min identity {df['identity_to_reference'].min():.3f} < {ALIGN_IDENTITY_FAIL:.2f}. "
    "Inspect low-identity rows before PLANT embedding."
)

# Explicit alignment QC on the raw (pre-trim) sequence vs reference before final CSV save.
qc_df = df["seq_raw"].apply(lambda s: pd.Series(alignment_coverage_metrics(s)))
df = pd.concat([df, qc_df], axis=1)

print("\nAlignment coverage summary (raw sequence vs reference):")
print(df[["aligned_ref_coverage", "aligned_query_coverage", "alignment_score"]].describe(percentiles=[0.05, 0.25, 0.5, 0.75, 0.95]))

low_ref_cov = df[df["aligned_ref_coverage"] < ALIGN_REF_COVERAGE_WARN].copy()
if len(low_ref_cov) > 0:
    print(f"WARNING: {len(low_ref_cov)} sequences below {ALIGN_REF_COVERAGE_WARN:.2f} reference coverage.")
    cols = [c for c in ["name", "subclade", "aligned_ref_coverage", "aligned_query_coverage", "alignment_score"] if c in low_ref_cov.columns]
    print(low_ref_cov[cols].sort_values("aligned_ref_coverage").head(20))

assert df["aligned_ref_coverage"].min() >= ALIGN_REF_COVERAGE_FAIL, (
    f"Alignment QC failed before save: min reference coverage {df['aligned_ref_coverage'].min():.3f} < {ALIGN_REF_COVERAGE_FAIL:.2f}. "
    "Inspect low-coverage sequences before PLANT embedding."
)

# Keep CSV compact; drop raw helper column before writing.
df = df.drop(columns=["seq_raw"])
# %%

df.to_csv(os.path.join(outdir, "PLANT_input_filtered.csv"), index=False)
# %%

# tokenizer & encodes
MODEL_NAME = "facebook/esm2_t33_650M_UR50D"
MAX_LENGTH = 329
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
enc_virus = tokenize_sequences(df["seq"].tolist(), tokenizer, MAX_LENGTH)

# Dataset / DataLoader
dataset = TextDataset(enc_virus)
loader  = DataLoader(dataset, batch_size=64, shuffle=False)

"""Inference"""


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# ESM Config
esm_config = EsmConfig.from_pretrained(MODEL_NAME, use_safetensors=True)

# Specify CKPT_DIR containing shards obtained from HF
model = semanticESM.from_pretrained(
    CKPT_DIR,
    config=esm_config,
    esm_model_name=MODEL_NAME,
    intermediate_dim=256,
    intermediate_dim_encoder=64,
)

model.to(device)
model.eval()
model.half()

# Inference (embed_sequences is a thin utility to extract hidden_state_virus and return as numpy)
Z = embed_sequences(model, loader, use_fp16=True)  # shape: (N, latent_dim=3)
print("Embeddings shape:", Z.shape)

# Store in DataFrame
df["X"], df["Y"], df["Z"] = (
    Z[:, 0] * scale_factor,
    Z[:, 1] * scale_factor,
    Z[:, 2] * scale_factor,
)

df.head()

# %%
# Calculate distance to reference
REF_NAME = "EPI2981619|HA|A/Croatia/10136RV/2023|EPI_ISL_18856647|J.2"

print(f"Calculating distances to reference: {REF_NAME}")
ref_row = df[df["name"] == REF_NAME]

if len(ref_row) == 0:
    print(f"Warning: Reference sequence '{REF_NAME}' not found in the dataframe.")
else:
    ref_x = ref_row.iloc[0]["X"]
    ref_y = ref_row.iloc[0]["Y"]
    ref_z = ref_row.iloc[0]["Z"]
    
    # Euclidean distance
    df["Distance_to_Ref"] = np.sqrt(
        (df["X"] - ref_x)**2 + 
        (df["Y"] - ref_y)**2 + 
        (df["Z"] - ref_z)**2
    )
    
    # Export CSV without sequences
    cols_to_export = [c for c in df.columns if c != "seq"]
    export_df = df[cols_to_export]
    
    export_path = os.path.join(outdir, "PLANT_embeddings_with_distance.csv")
    export_df.to_csv(export_path, index=False)
    print(f"Saved embeddings and distances to {export_path}")
    print(export_df.head())

"""Visualization, only data of interest"""



# Sort subclades alphabetically
subclade_order = sorted(df["subclade"].unique())

# Sample colors sequentially so adjacent subclades have similar colors
n = len(subclade_order)
colorscale = px.colors.sequential.Turbo
color_sequence = pc.sample_colorscale(colorscale, [i/(max(n-1, 1)) for i in range(n)])
# %%
print(df.tail())
# %%

fig_sub = px.scatter_3d(
    df,
    x="X", y="Y", z="Z",
    color="subclade",
    category_orders={"subclade": subclade_order},
    color_discrete_sequence=color_sequence,
    hover_name="name",
    hover_data={"subclade": True},
    opacity=0.8,
    title="Colored by subclade"
)
fig_sub.update_layout(height=1500, width=1500)
#fig_sub.show()

#savefig (as HTML to avoid needing Chrome)
fig_sub.write_html(os.path.join(outdir, "PLANT_embedding_subclade.html"))

# %%
# colour specifically J.2.2Eng24 , K, J.2.vaccine_column and make them bigger to make it more obvious

# Emphasized lineage view: highlight specified lineages, mute all others
target_lineages = ["J.2.2Eng24", "K", "J.2.vaccine_column"]
target_palette = {
    "J.2.2Eng24": "#e41a1c",
    "K": "#377eb8",
    "J.2.vaccine_column": "#4daf4a",
}

df_emph = df.copy()
df_emph["subclade_str"] = df_emph["subclade"].astype(str)
df_targets = df_emph[df_emph["subclade_str"].isin(target_lineages)].copy()
df_background = df_emph[~df_emph["subclade_str"].isin(target_lineages)].copy()

missing_targets = [x for x in target_lineages if x not in set(df_targets["subclade_str"].unique())]
if missing_targets:
    print(f"Warning: requested highlighted lineages not found in data: {missing_targets}")

fig_sub_emph = go.Figure()

# Background points (muted)
fig_sub_emph.add_trace(go.Scatter3d(
    x=df_background["X"],
    y=df_background["Y"],
    z=df_background["Z"],
    mode="markers",
    marker=dict(size=3, color="#c7c7c7", opacity=0.22, symbol="circle"),
    text=df_background.get("name", None),
    customdata=df_background[["subclade"]].values if "subclade" in df_background.columns else None,
    hovertemplate=(
        "name: %{text}<br>"
        "subclade: %{customdata[0]}<br>"
        "X: %{x:.3f}<br>Y: %{y:.3f}<br>Z: %{z:.3f}<extra>background</extra>"
    ) if "subclade" in df_background.columns else None,
    name="Other lineages",
    showlegend=True,
))

# Highlighted lineages (larger)
for lineage in target_lineages:
    sub_df = df_targets[df_targets["subclade_str"] == lineage]
    if len(sub_df) == 0:
        continue
    fig_sub_emph.add_trace(go.Scatter3d(
        x=sub_df["X"],
        y=sub_df["Y"],
        z=sub_df["Z"],
        mode="markers",
        marker=dict(size=10, color=target_palette.get(lineage, "#ff7f00"), opacity=0.95, symbol="circle"),
        text=sub_df.get("name", None),
        customdata=sub_df[["subclade"]].values if "subclade" in sub_df.columns else None,
        hovertemplate=(
            "name: %{text}<br>"
            "subclade: %{customdata[0]}<br>"
            "X: %{x:.3f}<br>Y: %{y:.3f}<br>Z: %{z:.3f}<extra>highlight</extra>"
        ) if "subclade" in sub_df.columns else None,
        name=lineage,
        showlegend=True,
    ))

fig_sub_emph.update_layout(
    title="PLANT embeddings (highlighted: J.2.2Eng24, K, J.2.vaccine_column)",
    scene=dict(xaxis_title="X", yaxis_title="Y", zaxis_title="Z"),
    height=1500,
    width=1500,
)
fig_sub_emph.write_html(os.path.join(outdir, "PLANT_embedding_subclade_emphasized.html"))
                    

# %%

fig_year = px.scatter_3d(
    df,
    x="X", y="Y", z="Z",
    color="year",
    color_continuous_scale="Viridis",
    hover_name="name",
    hover_data={"subclade": True, "year": True},
    opacity=0.8,
    title="Colored by year"
)
fig_year.update_layout(height=1500, width=1500)
#fig_year.show()
#savefig (as HTML to avoid needing Chrome)
fig_year.write_html(os.path.join(outdir, "PLANT_embedding_year.html"))

"""Visualization, showing all virus strains inferred in PLANT paper as background"""

background_df = pd.read_csv(BACKGROUND_CSV_PATH)

def extract_year(val):
    return plant_extract_year(val)

background_df["year"] = background_df["collection date"].apply(extract_year)

background_df.tail()



# Subclade order and colormap
subclade_order = sorted(
    set(df["subclade"].dropna().unique()).union(
        set(background_df["subclade"].dropna().unique())
    )
)
n = max(len(subclade_order), 1)
colorscale = px.colors.sequential.Turbo
color_seq = pc.sample_colorscale(colorscale, [i/(n-1) if n > 1 else 0.5 for i in range(n)])

# Create color map, but overwrite "unassigned" with gray
color_map = {clade: color_seq[i] for i, clade in enumerate(subclade_order)}
if "unassigned" in color_map:
    color_map["unassigned"] = "#BBBBBB"

# Background trace
trace_bg = go.Scatter3d(
    x=background_df["X"], y=background_df["Y"], z=background_df["Z"],
    mode="markers",
    marker=dict(
        size=2,
        opacity=0.85,
        symbol="diamond-open",
        color=[color_map.get(c, "#BBBBBB") for c in background_df["subclade"]],
    ),
    text=background_df.get("name", None),
    hovertemplate=(
        "name: %{text}<br>"
        "subclade: %{customdata[0]}<br>"
        "year: %{customdata[1]}<br>"
        "X: %{x:.3f}<br>Y: %{y:.3f}<br>Z: %{z:.3f}<extra>background</extra>"
    ),
    customdata=background_df[["subclade", "year"]].values,
    name="background",
    showlegend=False
)

# Main trace
trace_main = go.Scatter3d(
    x=df["X"], y=df["Y"], z=df["Z"],
    mode="markers",
    marker=dict(
        size=6,
        opacity=1,
        symbol="circle",
        color=[color_map.get(c, "#999999") for c in df["subclade"]],
    ),
    text=df.get("name", None),
    hovertemplate=(
        "name: %{text}<br>"
        "subclade: %{customdata[0]}<br>"
        "X: %{x:.3f}<br>Y: %{y:.3f}<br>Z: %{z:.3f}<extra>main</extra>"
    ),
    customdata=df[["subclade"]].values,
    name="main",
    showlegend=False
)

# Dummy traces for legend
legend_traces = []
for clade in subclade_order:
    legend_traces.append(
        go.Scatter3d(
            x=[None], y=[None], z=[None],
            mode="markers",
            marker=dict(size=6, color=color_map[clade]),
            name=clade
        )
    )

# Background trace
fig = go.Figure([trace_bg, trace_main] + legend_traces)
fig.update_layout(
    title="PLANT embeddings (shared color scheme by subclade)",
    scene=dict(xaxis_title="X", yaxis_title="Y", zaxis_title="Z"),
    legend=dict(itemsizing="constant", title="Subclade colors"),
    height=1500, width=1500
)
#fig.show()
#writefig (as HTML to avoid needing Chrome)
fig.write_html(os.path.join(outdir, "PLANT_embedding_background_subclade.html"))

# Take common min/max for year coloring
year_min = min(df["year"].min(), background_df["year"].min())
year_max = max(df["year"].max(), background_df["year"].max())

# Background trace
trace_bg = go.Scatter3d(
    x=background_df["X"], y=background_df["Y"], z=background_df["Z"],
    mode="markers",
    marker=dict(
        size=2,
        opacity=0.3,
        symbol="diamond-open",
        color=background_df["year"],
        cmin=year_min,
        cmax=year_max,
        colorscale="Viridis",
        colorbar=dict(title="Year")
    ),
    text=background_df.get("name", None),
    hovertemplate=(
        "name: %{text}<br>"
        "year: %{customdata[0]}<br>"
        "X: %{x:.3f}<br>Y: %{y:.3f}<br>Z: %{z:.3f}<extra>background</extra>"
    ),
    customdata=background_df[["year"]].values,
    name="background",
    showlegend=False
)

# Main trace
trace_main = go.Scatter3d(
    x=df["X"], y=df["Y"], z=df["Z"],
    mode="markers",
    marker=dict(
        size=6,
        opacity=1,
        symbol="circle",
        color=df["year"],
        cmin=year_min,
        cmax=year_max,
        colorscale="Viridis",
        showscale=False
    ),
    text=df.get("name", None),
    hovertemplate=(
        "name: %{text}<br>"
        "year: %{customdata[0]}<br>"
        "X: %{x:.3f}<br>Y: %{y:.3f}<br>Z: %{z:.3f}<extra>main</extra>"
    ),
    customdata=df[["year"]].values,
    name="main",
    showlegend=False
)

# Combine figure
fig = go.Figure([trace_bg, trace_main])
fig.update_layout(
    title="PLANT embeddings (colored by year)",
    scene=dict(xaxis_title="X", yaxis_title="Y", zaxis_title="Z"),
    height=1500, width=1500
)
#fig.show()
#writefig (as HTML to avoid needing Chrome)
fig.write_html(os.path.join(outdir, "PLANT_embedding_background_year.html"))


# %%
# go through each year of background_df and take centroid coordinates
print("Background DataFrame columns:", background_df.columns.tolist())

# Calculate centroid for each year
yearly_centroids = background_df.groupby('year')[['X', 'Y', 'Z']].mean().reset_index()
yearly_centroids.columns = ['year', 'centroid_X', 'centroid_Y', 'centroid_Z']

# Also add count of sequences per year
yearly_counts = background_df.groupby('year').size().reset_index(name='n_sequences')
yearly_centroids = yearly_centroids.merge(yearly_counts, on='year')

# Sort by year
yearly_centroids = yearly_centroids.sort_values('year')

print("\nYearly centroids for circulating strains:")
print(yearly_centroids.to_string(index=False))

# Save to CSV
yearly_centroids.to_csv(os.path.join(outdir, "yearly_centroids.csv"), index=False)

# Get recent years (last 5 years)
recent_years = yearly_centroids.nlargest(6, 'year')
print("\n\nRecent years centroids:")
print(recent_years.to_string(index=False))

# %%
#irrelevant stuff
# read in this and print all the difference from the last two sequence to the top sequence (ignore Xs)
#/home3/oml4h/PLM_SARS-CoV-2/Sequences/plus_extraHA_huH3N2_HA_CDS.translated_OM_synth_extra_steps (Copy).fas

fasta_file = "/home3/oml4h/PLM_SARS-CoV-2/Sequences/plus_extraHA_huH3N2_HA_CDS.translated_OM_synth_extra_steps (Copy).fas"

# Read FASTA file and parse sequences
sequences = []
current_seq = ""
current_header = ""

with open(fasta_file, 'r') as f:
    for line in f:
        line = line.strip()
        if line.startswith('>'):
            if current_header:
                sequences.append((current_header, current_seq))
            current_header = line[1:]  # Remove '>'
            current_seq = ""
        else:
            current_seq += line
    # Add last sequence
    if current_header:
        sequences.append((current_header, current_seq))

print(f"Found {len(sequences)} sequences\n")

# Get the first (reference) and last two sequences
ref_header, ref_seq = sequences[0]
second_last_header, second_last_seq = sequences[-2]
last_header, last_seq = sequences[-1]

# Find minimum length (to avoid going beyond where last sequence ends)
min_length = min(len(ref_seq), len(second_last_seq), len(last_seq))

print(f"Reference sequence: {ref_header}")
print(f"Second-to-last sequence: {second_last_header}")
print(f"Last sequence: {last_header}")
print(f"\nComparing up to position {min_length}\n")

# Compare second-to-last sequence to reference
print("="*80)
print(f"Differences: {second_last_header} vs {ref_header}")
print("="*80)
differences_second_last = []
for i in range(min_length):
    ref_aa = ref_seq[i]
    query_aa = second_last_seq[i]
    # Ignore X's
    if ref_aa != 'X' and query_aa != 'X' and ref_aa != query_aa:
        differences_second_last.append((i+1, ref_aa, query_aa))
        print(f"Position {i-15}: {ref_aa} -> {query_aa}")

if not differences_second_last:
    print("No differences found (ignoring X's)")
print(f"\nTotal differences: {len(differences_second_last)}\n")

# Compare last sequence to reference
print("="*80)
print(f"Differences: {last_header} vs {ref_header}")
print("="*80)
differences_last = []
for i in range(min_length):
    ref_aa = ref_seq[i]
    query_aa = last_seq[i]
    # Ignore X's
    if ref_aa != 'X' and query_aa != 'X' and ref_aa != query_aa:
        differences_last.append((i+1, ref_aa, query_aa))
        print(f"Position {i-15}: {ref_aa} -> {query_aa}")

if not differences_last:
    print("No differences found (ignoring X's)")
print(f"\nTotal differences: {len(differences_last)}")

